#!/usr/bin/perl

use strict;
use DBI;
use JSON;
use Image::ExifTool ':Public';
use File::Find;
use Data::Printer;
use Data::Dumper;
use Digest::MD5;

my $dbh = 0; # global database handle

sub connect_database {
  my $driver = "SQLite";
  my $database = "media.db";
  my $dsn = "DBI:$driver:dbname=$database";
  my $userid = "";
  my $password = "";
  my $dbh = DBI->connect($dsn, $userid, $password, { RaiseError => 1 })
    or die $DBI::errstr;
  return $dbh;
}

sub digest_from_file($) {
  my $file = @_[0];
  my $md5 = Digest::MD5->new;
  open(my $F, $file) or die $!;
  return Digest::MD5->new->addfile($F)->hexdigest;
}

sub hash_to_json($) {
  my %info = %{@_[0]};
  my %ihash;
  my $json = JSON->new();

  $json->pretty(1);

  foreach (sort keys %info) {
    my $val = $info{$_};
    my ($year, $month, $day, $rest);

    # change DateTime values into a format SQLite can understand
    if ($_ =~ "Date") {
      if (($year, $month, $day, $rest) = $val =~ /^(\d{4}):(\d{2}):(\d{2}) (.*)$/) {
        $val = "$year-$month-$day $rest";
      }
    }
    if (ref $val eq 'ARRAY') {
      $val = join(', ', @$val);
    } elsif (ref $val eq 'SCALAR') {
      $val = '(binary)';
    }
    $ihash{$_} = $val;
  }
  return $json->encode(\%ihash);
}

sub insert_into_db($$$$$$$$$$$$$$) {
  my ($dbh, $path, $filename, $ext, $size, $mtime, $digest, $exif, $width, $height, $duration, $lat, $lon, $camera) = @_;
  my $sql = qq[INSERT INTO media(path, filename, ext, size, mtime, digest, exif, width, height, duration, lat, lon, camera)
                      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)];
  my $sth = $dbh->prepare($sql);
  $sth->execute($path, $filename, $ext, $size, $mtime, $digest, $exif, $width, $height, $duration, $lat, $lon, $camera)
    or die "$DBI::errstr: $path, $digest";
}

# converts a string to seconds, possible variants
# 8.24 s
# 0:07:00
# returns number of seconds
sub duration_to_seconds($) {
  my ($s) = @_;
  my ($hour, $min, $sec, $msec);

  if (($sec) = $s =~ /^([.\d]+) s$/) {
    # don't do anything just now
  } elsif (($hour, $min, $sec) = $s =~ /^(\d{1,2}):(\d{2}):(\d{2})$/) {
    # don't do anything just now
  } else {
    die "'$s': I don't understand this string";
  }
  print "Duration=", ($hour * 3600 + $min * 60 + $sec), "sec\n";
  return ($hour * 3600 + $min * 60 + $sec);
}

sub get_height(%) {
  my (%info) = @_;
  my $h = $info{'ImageHeight'};
  if (!defined($h)) {
    $h = $info{'ExifImageHeight'};
  }
  # print "height=$h\n";
  return $h;
}

sub get_width(%) {
  my (%info) = @_;
  my $w = $info{'ImageWidth'};
  if (!defined($w)) {
    $w = $info{'ExifImageWidth'};
  }
  # print "width=$w\n";
  return $w;
}

# get fileextension, can be jpg or jpeg, webm, m2ts, mts etc.
sub get_extension($) {
  my ($fname) = @_;
  my $ext = '';

  my $dot = rindex($fname, '.');
  if ($dot > -1) {
    $ext = lc substr($fname, $dot+1);
  }
  # print "ext=$ext\n";
  return $ext;
}

# return 1 to ignore the path or 0 to process the path
sub ignore_path($) {
  my ($path) = @_;
  if ($path =~ /\/Program Files\/|\/Program Files \(x86\)|ProgramData|\$Recycle\.Bin|\/AppData\/|\/mnt\/.\/Windows/i) {
    return 1;
  } else {
    return 0;
  }
}

sub process_file($$) {
  my ($dbh, $fname) = @_;
  my ($duration, $width, $height, $seconds, $json_exif, $digest, @st, $info, $ext,
      $lat, $lon, $camera);

  if (ignore_path($fname)) {
    return;
  }

  @st = stat($fname); # file size
  if ($st[7] < (64 * 1024)) {
    # print "ignored: $File::Find::name\n";
    return;
  }

  $info = ImageInfo($fname);

  $duration = %$info{'Duration'};
  $seconds = duration_to_seconds($duration) if $duration;

  $width = get_width(%$info);
  $height = get_height(%$info);
  $ext = get_extension($fname);
  $lat = %$info{'GPSLatitude'};
  $lon = %$info{'GPSLongitude'};
  $camera = %$info{'Model'};
  $json_exif = hash_to_json($info);
  $digest = digest_from_file($File::Find::name);
  insert_into_db($dbh, $File::Find::name, $_, $ext, $st[7], $st[9], $digest, $json_exif,
                 $width, $height, $seconds, $lat, $lon, $camera);
}

sub wanted {
  if (-f and /\.(jpeg|jpg|png|mts|m2ts|avi|webm|mp4|mks|mkv)$/i) {
    print "$File::Find::name\n";
    process_file($main::dbh, $File::Find::name);
  }
}

sub preprocess {
  # print "preprocess $File::Find::dir\n";
  # print @_;
  if (ignore_path($File::Find::dir)) {
    print "ignore directory $File::Find::dir\n";
    return [];
  } else {
    return @_;
  }
}

# main starts here

my @dirs = @ARGV;

p @dirs;

$main::dbh = connect_database();

find({wanted => \&wanted, follow => 0, preprocess => \&preprocess}, @dirs);

$main::dbh->disconnect();
__DATA__
select path, (select j.value from json_each(t.exif) AS j WHERE j.key = 'CreateDate') AS data from media as t where data is null;
